apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: default  # Remplacez par le namespace de votre application
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"  # Désactiver Pod Identity
    useVMManagedIdentity: "false"  # Désactiver l'identité managée de la VM
    useWorkloadIdentity: "true"  # Activer Workload Identity
    clientID: "15d381be-9935-4d9a-b835-242e48880323"  # Remplacez par l'ID client de l'identité Azure AD
    keyvaultName: "kv-itgalaxy-production"  # Remplacez par le nom de votre Key Vault
    cloudName: "AzurePublicCloud"  # Environnement Azure (par défaut: AzurePublicCloud)
    objects: |
      array:
        - |
          objectName: dbPwd # Nom du secret dans Azure Key Vault
          objectType: secret  # Type de l'objet (secret, key, ou cert)
          objectVersion: ""  # Version du secret (vide pour la dernière version)
        - |
          objectName: test # Nom du secret dans Azure Key Vault
          objectType: secret  # Type de l'objet (secret, key, ou cert)
          objectVersion: ""  # Version du secret (vide pour la dernière version)
    tenantId: "4f4d7e31-b44d-4ef2-94d5-db783bc2b1f6"  # Remplacez par l'ID du locataire Azure AD
