---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 670270766287.dkr.ecr.eu-west-1.amazonaws.com/workshop-eks/ui:~v0.1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/Itgalaxy1/workshopeks/applications/ui.git
    targetRevision: main
    path: helm-ui-chart
    helm:
      parameters:
        - name: "replicaCount"
          value: "1"
        - name: "image.repository"
          value: 670270766287.dkr.ecr.eu-west-1.amazonaws.com/workshop-eks/ui
        - name: "image.tag"
          value: v0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
