apiVersion: v1
kind: Secret
metadata:
  name: argoproj-https-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://gitlab.com/Itgalaxy1/workshopeks/applications/ui.git
  username: itgalaxy  # Peut être n'importe quoi, car GitLab utilise le token pour l'authentification
  password: Z2xwYXQtcGdnRVhiY3NzMzBOeXZpdHY1X2lDbTg2TVFwMU9tSmxjemR3Q3cuMDEuMTIwd210ZzR2Cg== # Remplacez par votre token GitLab