stages:
  - deploy

before_script:
  - apk add --no-cache curl jq python3 py3-pip
  - pip install awscli
  - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
  - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
  - aws configure set region "$AWS_DEFAULT_REGION"


deploy-staging:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY
    - docker build -t $TAG .
    - docker push $TAG
    #- aws ecs update-service --cluster $CLUSTER --service $SERVICE_API_CHAT --force-new-deployment --region eu-west-1
  only:
    - develop
  environment:
    name: staging    

deploy-prod:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY
    - docker build -t $TAG .
    - docker push $TAG
   # - aws ecs update-service --cluster $CLUSTER --service $SERVICE_API_CHAT --force-new-deployment --region eu-west-1
  only:
    - main
  environment: 
    name: production
