version: '3.8'
services:
  app-prod:
    image: bolt-ai:production
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-production
    ports:
      - "5173:5173"
    env_file: ".env.local"
    environment:
      - GOOGLE_GENERATIVE_AI_API_KEY=AIzaSyBxu7srK61CRYSM22DoHOIPv9b2HAAMAi0
    command: pnpm run dockerstart
